### ISSUE TITLE
与基岩版移植的在线构建联动

### ISSUE THREAD

**Issue by lakejason0** [Teahouse-Studios/mcwzh-meme-resourcepack#105]
**你的特性建议和某个问题相关吗？请描述。**
隔壁基岩版的构建脚本年久失修，也不能适应在线打包。

**描述你喜欢的解决方法**
帮基岩版也做一个。

**附加信息**
请有能力的人来维护基岩版，谢谢大家。
这是一个联动issue。基岩版见[这里](https://github.com/Teahouse-Studios/mcwzh-meme-resourcepack-bedrock/issues/9)。

**Comment by XxLittleCxX** [comment]
你是想接入在一个页面还是分开的两个网页 @lakejason0

**Comment by lakejason0** [comment]
> 你是想接入在一个页面还是分开的两个网页 @lakejason0

你们方便实现就行。

**Comment by lakejason0** [comment]
@Teahouse-Studios/memified-chinese-content-group

**Comment by zbwxtex** [comment]
> @Teahouse-Studios/memified-chinese-content-group

啥玩意?

**Comment by lakejason0** [comment]
> > @Teahouse-Studios/memified-chinese-content-group
> 
> 啥玩意?

工作室内部ping。

**Comment by dianliang233** [comment]
建议改成：傻瓜式构建

**Comment by AlPha5130** [comment]
基岩版的问题写到这里干什么...

**Comment by lakejason0** [comment]
> 基岩版的问题写到这里干什么...

“联动”问题，当初有计划将同一个网页打包不同的版本来着（

**Comment by AlPha5130** [comment]
主体内容已完成，其他问题不属于此issue。
