### ISSUE TITLE
迁出前端部分至单独的repo

### ISSUE THREAD

**Issue by AlPha5130** [Teahouse-Studios/mcwzh-meme-resourcepack#106]
考虑基岩版的在线构建，为了减少重复代码和工作量，同时实现本repo的前后端分离，故建议将前端部分迁移至单独的repo中。

**Comment by AlPha5130** [comment]
per #105

**Comment by lakejason0** [comment]
`mcwzh-meme-resourcepack-web-builder`？

**Comment by XxLittleCxX** [comment]
See https://github.com/Teahouse-Studios/mcwzh-meme-web-builder

**Comment by AlPha5130** [comment]
Already done.
