### ISSUE TITLE
基岩版梗体中文无人同步更新

### ISSUE THREAD

**Issue by SkyEye-FAST** [Teahouse-Studios/mcwzh-meme-resourcepack#110]
目前基岩版梗体中文只有我**一个人**在同步更新。

同步更新方式早已写在[CONTRIBUTING.md](https://github.com/Teahouse-Studios/mcwzh-meme-resourcepack-bedrock/blob/master/CONTRIBUTING.md)中，但是无人照此去做。

请求以后在更新Java版语言文件内容时劳烦**同时**同步至基岩版，万分感谢。

**Comment by lakejason0** [comment]
知道了。

**Comment by lakejason0** [comment]
另，@Teahouse-Studios/memified-chinese-content-group

**Comment by AlPha5130** [comment]
讨论转移至内容组。
