### ISSUE TITLE
部分模组翻译字符串有误

### ISSUE THREAD

**Issue by teddyxlandlee** [Teahouse-Studios/mcwzh-meme-resourcepack#111]
terrestria模组的各种原木未改成XX日志，而是保留XX木（甚至不是XX原木！望修改）
其他模组和Minecraft原版没有该问题。
![image](https://user-images.githubusercontent.com/67260053/89616964-e2932700-d8bb-11ea-8f83-5c86cfee853a.png)

**Comment by lakejason0** [comment]
若能提供terrestria最新的语言文件的话感激不尽。

**Comment by lakejason0** [comment]
Mod统一性并非最优先考虑的事项（因为Mod多，也很杂），马上受理。

**Comment by lakejason0** [comment]
原来的翻译就不太符合原版的格式，so先把船修掉。

**Comment by lakejason0** [comment]
日志改掉了。
Closed #111.
