### ISSUE TITLE
文字修改建议

### ISSUE THREAD

**Issue by chelwr** [Teahouse-Studios/mcwzh-meme-resourcepack#112]
在给俺的服务器制作专属生草翻译包时，我发现字符都使用了**Unicode**
因为我觉得这么修改过于麻烦，所以便查找出了一个轻松的好办法。
使用VSCode的[native-ascii-converter](https://marketplace.visualstudio.com/items?itemName=cwan.native-ascii-converter)插件，能够在编辑*.properties文件时自动将unicode转化为“人看的字”,然后对其编辑，并且在保存时将我们加的字与本来就有的字转换回来到Unicode。
所以在*.properties文件下编辑，然后复制到json也许是一个不错的点子。
由于我本人不知道你们是怎么进行制作的，所以我不确定这个方法是否适合你们

**Comment by lakejason0** [comment]
哦，想要一份单独的非ASCII文件。
之前在打包脚本里有一个调试模式，就是为了输出一份无转码的格式。
目前这个功能因为前端和重构问题已经被移除了。

**Comment by lakejason0** [comment]
如果你不会使用命令行的脚本的话，之后我们会提供一份文档（因为一直在重构）。

**Comment by lakejason0** [comment]
另外，在构建的时候自动的转换编码是有意设计的。

**Comment by chelwr** [comment]
所以更改语言文件不需要使用Unicode直接输入也能成功吗🤔

**Comment by lakejason0** [comment]
你可以尝试把整个repo下载下来。你会发现存在一份汉字的梗体中文的本体文件（不含Mod）。
