### ISSUE TITLE
【紧急】最新的构建脚本故障

### ISSUE THREAD

**Issue by Dianliang233** [Teahouse-Studios/mcwzh-meme-resourcepack#116]
最新 v1.0.0 的构建脚本会报错。目前网页构建已经失效。

**Comment by XxLittleCxX** [comment]
Fixed. https://github.com/Teahouse-Studios/mcwzh-meme-resourcepack/commit/1e632dae2297bb17dca8b7dda4f5d91704a0bab9 https://github.com/Teahouse-Studios/mcwzh-meme-resourcepack/commit/6f0c770dcdb41c9087d142802dd6b122dbbed1ec
