### ISSUE TITLE
v1.0.1 pack.mcmeta 版本未修改

### ISSUE THREAD

**Issue by WindLeaf233** [Teahouse-Studios/mcwzh-meme-resourcepack#117]
**描述**
版本 v1.0.1 在使用过程中发现 pack.mcmeta 中的 Pre-release 没有改，还是 Pre-release v0.11.0

**复现步骤**
复现漏洞的步骤：

1. 打开了 Minecraft 1.16.2
2. 从 Github 下载并装载了 mcwzh-meme
3. 发现资源包说明的第二行出现问题

**正常行为**
Pre-release 应为 v1.0.1

**截图**
![QQ截图20200826123448](https://user-images.githubusercontent.com/58383985/91255989-c4249b00-e798-11ea-9d86-93b34c5c8c7e.png)

**版本**
Minecraft 1.16.2
mcwzh-meme v1.0.1

* 操作系统：Windows 7 x64
* Minecraft 版本：1.16.2
* 资源包版本：1.0.1
* 环境：原版

**其他内容**
无

**Comment by WindLeaf233** [comment]
pack.mcmeta 不会要让我们自己 build 吧？

**Comment by Dianliang233** [comment]
Fixed
