### ISSUE TITLE
添加模组梗化 / Add Mod Memilization

### ISSUE THREAD

**Issue by teddyxlandlee** [Teahouse-Studios/mcwzh-meme-resourcepack#119]
我是Sweet Potato Mod的作者之一teddyxlandlee。很喜欢这个资源包，所以**特地为自己的模组做了梗化**。  
语言文件：[传送门](https://github.com/teddyxlandlee/sweet_potato-source/blob/master/src/main/resources/assets/sweet_potato/lang/zh_meme.json)  
如有需要修改的地方，请指出。  
<br />
I am one of the authors of Sweet Potato Mod. I like this resource pack, so I memilize it by myself.  
Lang: [Portal](https://github.com/teddyxlandlee/sweet_potato-source/blob/master/src/main/resources/assets/sweet_potato/lang/zh_meme.json)  
Please point out if it should be edited

**Comment by XxLittleCxX** [comment]
个人感觉不错,不过您有一处文本内容在简体中文和梗体中文里没有翻译.

https://github.com/teddyxlandlee/sweet_potato-source/blob/556bd352cd915f774e3415a2d08c11e6a61d04b0/src/main/resources/assets/sweet_potato/lang/en_us.json#L16

**Comment by masnn** [comment]
test

**Comment by XxLittleCxX** [comment]
如果有需要,您可以按 [CONTRIBUTING.md](https://github.com/Teahouse-Studios/mcwzh-meme-resourcepack/blob/master/CONTRIBUTING.md)  中的步骤,将语言文件合并到本仓库中. 但由于您自己提供了语言文件, 不用进行这样额外的操作. 感谢您的支持,如有问题请reopen.

**Comment by teddyxlandlee** [comment]
~~没有翻译的地方是正常的，因为一开始它本来就没有翻译~~  
我们打算在未来一周内加入其官方的名称

**Comment by teddyxlandlee** [comment]
另外说一下我们模组梗化后的Peter Yang, Peter Zheng, Dennis等名字均为本模组开发人员及其身边的人
