### ISSUE TITLE
把书架的生草翻译改为书山压力大？

### ISSUE THREAD

**Issue by ColdStarxuan** [Teahouse-Studios/mcwzh-meme-resourcepack#120]
个人认为书山压力大 非常适合书架有很多书。

**Comment by Dianliang233** [comment]
请求进一步解释。

**Comment by lakejason0** [comment]
书山压力大是梗体的Colla， @Gu-ZT 。

**Comment by lakejason0** [comment]
那么既然是这样的话，把这玩意给图书管理员吗？

**Comment by AlPha5130** [comment]
> 那么既然是这样的话，把这玩意给图书管理员吗？

本人不赞同这样更改。

**Comment by lakejason0** [comment]
> > 那么既然是这样的话，把这玩意给图书管理员吗？
> 
> 本人不赞同这样更改。

的确，没有茵蒂克丝有名。

**Comment by ColdStarxuan** [comment]
我个人是希望扔给书架的，书架由三本书合成，然后一块块堆成小山状，然后压下来，嗯。。大概就这样

**Comment by ColdStarxuan** [comment]
或者单单改成：书山 也可以。
