### ISSUE TITLE
建议加入：世 界 名 画

### ISSUE THREAD

**Issue by MagentaSS** [Teahouse-Studios/mcwzh-meme-resourcepack#127]
**你的特性建议和某个问题相关吗？请描述。**
简明扼要地描述问题所在。例：我在看到世界名画一点都不“名”的时候很不爽。

**描述你喜欢的解决方法**
简明扼要地描述你想要的东西。譬如一幅1x2的希望之花。

**附加信息**
可以在此加上事情的来龙去脉或者关于这个特性建议的截图。
![抽象希望之花](https://user-images.githubusercontent.com/33283267/94884048-efd52800-049e-11eb-9c47-3c1725d9b552.png)
最好挂上世 界 名 画后可以看到类似于这样的

P.S.鉴于潜影壳的形状，建 议 改 成：“用珀珀块搭建的连门都不加的火柴盒”

**Comment by lakejason0** [comment]
这也太地狱绘图了……
迫害团长还行，但是不确定能不能塞得下。

**Comment by MagentaSS** [comment]
塞得下是指存储空间吗，应该做成16x32的像素画之类的，这么大是为了方便看
随手画的不要在意 （

**Comment by lakejason0** [comment]
主要是模块化已经更改了很多画了，不确定有无更多的空间放。
顺便，似乎有点太随便了@Lxazl5770好像不是很想要

**Comment by MagentaSS** [comment]
抱歉，不怎么会画(

**Comment by AlPha5130** [comment]
因原作者已有两周未回复此issue，现将其关闭。
