### ISSUE TITLE
音游梗系列建议

### ISSUE THREAD

**Issue by HMIHemingway** [Teahouse-Studios/mcwzh-meme-resourcepack#128]
**你的特性建议和某个问题相关吗？请描述。**
与问题无关

**描述你喜欢的解决方法**
添加“t+pazolite - IZANA”（哪里功夫高），"Sulfur"（Sulfar），“M2U - Gravity”（高昏！爽wwww）等音游名曲（一部分曲目需在电台下载）
添加大佬的成绩结算图作为“世界名画”
土豆改为“616服务器”，工作台改为“手台”等
死亡提示添加“(Player)在打(Enemy)时回忆率过低”等
（抱歉咱暂时想不到其它的了）

**描述你想到的其他解决方案**
可以整出一个新的语言（）

**附加信息**
RT，之前投错位置了（挠头）

**Comment by lakejason0** [comment]
音游名曲……抱歉塞不下，早就占满了。
世界名画的尺寸很小，糊了就不好了。当然，只要比例对就行，所以应该还能塞……？
土豆……抱歉果然还是育碧梗更有名一些（这个包现在有一点出名不太能随便塞冷门梗）
死亡提示添加吗……你可以举一个死亡的场合，因为我也不知道该塞在哪里。
手台……emmm。

**Comment by XxLittleCxX** [comment]
手台有点歧义吧，直接搜```手台```并不是音游的东西（

**Comment by HMIHemingway** [comment]
啊这
比如A被小白杀死了，则提示“A在打小白时回忆率过低”
手台有歧义可以换成“山东维系手台”
世界名画可以塞“10001279”“MM”之类（当然咱不保证塞的下）

**Comment by Dianliang233** [comment]
我认为死亡提示可以。



---原始邮件---
发件人: "HMIHemingway"<notifications@github.com&gt;
发送时间: 2020年10月3日(周六) 中午12:26
收件人: "Teahouse-Studios/mcwzh-meme-resourcepack"<mcwzh-meme-resourcepack@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: Re: [Teahouse-Studios/mcwzh-meme-resourcepack] 音游梗系列建议 (#128)




 
啊这
 比如A被小白杀死了，则提示“A在打小白时回忆率过低”
 手台有歧义可以换成“山东维系手台”
 世界名画可以塞“10001279”“MM”之类（当然咱不保证塞的下）

**Comment by AlPha5130** [comment]
因原作者已有两周未回复此issue，现将其关闭。
