### ISSUE TITLE
1.12.2材质包无效果

### ISSUE THREAD

**Issue by HMIHemingway** [Teahouse-Studios/mcwzh-meme-resourcepack#129]
**描述**
安装材质包后文字未按预期变动

**复现步骤**
复现漏洞的步骤：

1. 构造材质包，选择1.11~1.12.2
2. 移动至MC 1.12.2的文件夹
3. 打开游戏，激活材质包
4. 查看错误

**正常行为**
UI和物品的文字应出现变动，如：土豆→育碧服务器

**版本**

* 操作系统：Windows 10
* Minecraft 版本：1.12.2
* 资源包版本：1.0.4
* 环境：加载了Forge，安装了CustomSkinLoader，自定义NPC，JEI

**其他内容**
将zh_cn.json拓展名改为lang后仍然无效，推测可能构建时采用了新版MC的某些形式 ~~（瞎说一通）~~

**Comment by lakejason0** [comment]
?居然还是.json

**Comment by lakejason0** [comment]
尚不确定是前端传参还是后端脚本的问题，尝试复现。

**Comment by lakejason0** [comment]
问题已复现。

**Comment by HMIHemingway** [comment]
等会咱似乎在Closed中看到了类似的问题

**其它发现**
zh_cn文件中发现“tutorial”等异常字符串，推测使用了新版的文件

**Comment by lakejason0** [comment]
> 等会咱似乎在Closed中看到了类似的问题
> 
> **其它发现**
> zh_cn文件中发现“tutorial”等异常字符串，推测使用了新版的文件

wai

**Comment by lakejason0** [comment]
看上去是选项不对劲……

**Comment by lakejason0** [comment]
奇怪，后端的预设打包是正常的。

**Comment by lakejason0** [comment]
已确认。

**Comment by lakejason0** [comment]
等待 @XxLittleCxX 修复。
前端逻辑写的有问题。
