### ISSUE TITLE
Crash at 1.16.3

### ISSUE THREAD

**Issue by BlueSword03** [Teahouse-Studios/mcwzh-meme-resourcepack#130]
**描述**
加载材质包导致闪退

**复现步骤**
复现漏洞的步骤：

1. 加载材质包
2. 贴图未加载（bugjump的那张）

**正常行为**
无响应后闪退

**截图**
![image](https://user-images.githubusercontent.com/62334979/95070521-cf28fe80-073a-11eb-801a-2430f8500796.png)

**版本**

* 操作系统：Windows10 2004 专业工作站版
* Minecraft 版本：1.16.3
* 资源包版本：1.0.4 15ed78a
* 环境 原版无插件

**log**
[crash-2020-10-05_18.46.03-client.txt](https://github.com/Teahouse-Studios/mcwzh-meme-resourcepack/files/5326871/crash-2020-10-05_18.46.03-client.txt)

**Comment by lakejason0** [comment]
无插件当然没效果。
正在尝试复现无响应。

**Comment by lakejason0** [comment]
似乎没法复现。

**Comment by lakejason0** [comment]
崩溃问题可能是您的配置（内存）不够导致的，与资源包无关。
如果您的设备有足够多的内存，请在启动器设置中调整。
Bugjump的Logo仅当加载了OptiFine（或者类似的存在允许覆盖Mojang专有贴图功能的Mod）才可以出现。

**Comment by XxLittleCxX** [comment]
![image](https://user-images.githubusercontent.com/26459759/95071921-000a3300-073d-11eb-92e5-617a13802813.png)

请检查是否安装了32位的Java，如有，请更换为64位。

**Comment by BlueSword03** [comment]
好了，加大内存，加入OptiFine，再吧Java换成64位，好了
