### ISSUE TITLE
01

### ISSUE THREAD

**Issue by TIMEKL111** [Teahouse-Studios/mcwzh-meme-resourcepack#131]
可以把多人游戏改成   多♂人运♂动

**Comment by XxLittleCxX** [comment]
参见 https://github.com/Teahouse-Studios/mcwzh-meme-resourcepack/pull/69

**Comment by lakejason0** [comment]
陈年老梗，早就有过的建议了。
基岩版目前已实装一部分，Java版暂不考虑。
