### ISSUE TITLE
请发布烤地瓜模组作者名单更正公告

### ISSUE THREAD

**Issue by teddyxlandlee** [Teahouse-Studios/mcwzh-meme-resourcepack#136]
贵工作室之前弄错了我们的作者名单，在几分钟前业已更正。  
我们希望贵工作室在本仓库的[README.md](https://github.com/Teahouse-Studios/mcwzh-meme-resourcepack/blob/master/README.md)以及[MCBBS](https://www.mcbbs.net)发布更正公告，
因为我们认为贵工作室的失误可能会对用户对我们的印象有不利影响。  
  
Pigeonia Featurehouse（烤地瓜模组创作团队）

**Comment by lakejason0** [comment]
很抱歉，检查过我自己个人所管理的帖子和材料后，我发现所有有关注度的材料上根本就没有提及贵团队的具体成员。
换句话，你发公告给谁看？大部分的人是不用Mod内容的，也很少有人会注意到梗体中文居然也适配了一部分Mod。
个人认为commit记录里有，之后的发布成品没有您所说的不合适的内容就已经足够消除影响了，对于那些使用了网页打包的资源包，我们更没有任何权限和精力去追回。
希望贵工作室和我们能够正确认识到此事件的关注度，不要小题大做，反而把事情搞得双方都难过。

**Comment by XxLittleCxX** [comment]
https://github.com/teddyxlandlee/sweet_potato-source/commit/371212b25033e43ac4727ba20ed02766e7c97351
https://github.com/teddyxlandlee/sweet_potato-source/commit/facc82a47df20273dfaf30171eb51d2a6e22c567
据了解，```Pigeonia Featurehouse```这个团队名称是在 https://github.com/Teahouse-Studios/mcwzh-meme-resourcepack/issues/119 发布后才公布的，我们没有watch您仓库并在梗体中文中修改您的作者名的义务，更多观点可参见@lakejason0的回复，谢谢。

**Comment by teddyxlandlee** [comment]
好的，谢谢
