### ISSUE TITLE
Optifine部分字符串缺失

### ISSUE THREAD

**Issue by ly040519** [Teahouse-Studios/mcwzh-meme-resourcepack#137]
部分翻译丢失
![}96(_U5K0AL)I2}_3~4SPP9](https://user-images.githubusercontent.com/75530031/101243647-9908fa80-373c-11eb-999d-9ed978c683c9.png)

**Comment by lakejason0** [comment]
您需要使用带有Optifine的额外翻译的在线构建。

如果发现mod内容无法生效，请进一步汇报。

**Comment by lakejason0** [comment]
我们没有时间去快速跟进Mod的新版本翻译。

但是看截图，应该是干脆没有任何的Optifine翻译被载入。

**Comment by Dianliang233** [comment]
本 issue 闲置过久，报告者没有提供进一步信息，现予以关闭。若有进一步问题请 reopen。
