### ISSUE TITLE
一点问题

### ISSUE THREAD

**Issue by ly040519** [Teahouse-Studios/mcwzh-meme-resourcepack#138]
两个地方莫得翻译
![@Z 6JR 73ZOT$8F%R(G)CEQ](https://user-images.githubusercontent.com/75530031/102002757-bb050d00-3d3a-11eb-880a-52c6c121cf8b.png)
![MO7`XWM437_KON27N6V7MVM](https://user-images.githubusercontent.com/75530031/102002759-bb9da380-3d3a-11eb-84c2-03bd7abdb7b8.png)
（一个是武器的攻击力和攻速，还有一个是终极奉献）

**Comment by ly040519** [comment]
![W)WKN37M26WN3KZB$JUVAO8](https://user-images.githubusercontent.com/75530031/102004374-150dce80-3d4b-11eb-9e0c-b75d9f88a22d.png)
![G)V)1M UF84~LFFC8QFUW3R](https://user-images.githubusercontent.com/75530031/102004377-16d79200-3d4b-11eb-87a7-5dd95b80f2fc.png)
版本 1.16.3 fabric
mod，材质：附件
对于梗体中文材质：删除了草和太阳花还有painting中的图片
重新构建材质时发现的问题：mod支持选项中选择全部并不会加上optfine的翻译（以及**mod loaders）

**Comment by lakejason0** [comment]
hmm

@Teahouse-Studios/memifed-chinese-builder-group

**Comment by XxLittleCxX** [comment]
https://github.com/Teahouse-Studios/mcwzh-meme-web-builder/commit/d2212befbca3455aecbea5577c3e48bede8fc795
等待CI构建

**Comment by Dianliang233** [comment]
本 issue 闲置过久，疑似已修复，现予以关闭。若有进一步问题请 reopen。
