### ISSUE TITLE
给烤地瓜添加兼容模式

### ISSUE THREAD

**Issue by teddyxlandlee** [Teahouse-Studios/mcwzh-meme-resourcepack#148]
我们非常支持贵资源包的发展，并且在自家仓库和归档中添加了自己搞的`zh_meme.json`。可惜当使用Compatible Version的时候无法加载我们的梗体中文翻译。希望贵茶馆可以尽快安排上~  
  
翻译 [传送门](https://github.com/Featurehouse/sweet_potato-source/blob/1.16.3/src/main/resources/assets/sweet_potato/lang/zh_meme.json) | 
[~~截至2021年2月12日的翻译~~](https://github.com/Featurehouse/sweet_potato-source/blob/811b47b7e71d05012c22053fb4555c8daf73dd5b/src/main/resources/assets/sweet_potato/lang/zh_meme.json)  
  
另：我们把敝模组的梗体中文等语言的翻译搬到了[Crowdin](https://crowdin.com/project/spm)上，以方便梗体中文的粉丝与我们的粉丝为这两个项目贡献力量！  
  
Pigeonia Featurehouse  
12 Feb 2021

**Comment by Dianliang233** [comment]
贵工作室：

新年快乐！

感谢贵工作室对我资源包的支持。您的请求我们已经收到。

因技术原因，若您需要维护您的梗体中文翻译，则我们无法提供兼容版本的翻译。

若您同意转移翻译，请您提交 PR。关于 Crowdin，若您同意转移，则无法使用。

我们另提供备选方案，即您更新语言文件后自行推送至本仓库。

关于选择何种方案，请您根据贵工作室情况自行决定。

感谢！

**Comment by teddyxlandlee** [comment]
我们已经将翻译提交到#149.
敝工作室将继续维护本模组的梗体中文翻译，并在有更新的时候前来对线发PR
感谢茶馆工作室对Pigeonia Featurehouse的支持！
