### ISSUE TITLE
部分想法

### ISSUE THREAD

**Issue by zhyf0610** [Teahouse-Studios/mcwzh-meme-resourcepack#150]
**以下是个人的一些想法：**
苹果-----纽约/New York/牛顿快乐果
圆石-----石子（可以考虑叠字）
基岩-----砍手岩
红砖-----板砖
鹦鹉螺-----小螺号
命名牌-----狗牌
凋零骷髅头颅------非洲骷髅头颅（同步）
沙砾-----石乐（志）

**感觉上的bug--不是重点**
1.16.5 原版 
木桶在创造模式下没改名
![图片](https://user-images.githubusercontent.com/42296671/107966432-d0badb00-6fe6-11eb-9d4e-4b4a26681ac2.png)

盔甲韧性和击退抗性为英文
![图片](https://user-images.githubusercontent.com/42296671/107966458-d7e1e900-6fe6-11eb-91a9-0705b53754dd.png)

**Comment by lakejason0** [comment]
1. 砍手岩已于近日对Grimstone的更新中加入。
2. 鹦鹉螺感觉可以干脆把整句歌词都加进来。虽然我不确定加进去好不好。
3. 子的叠字的来源是一次转换表事故，不适用于所有的子，只适用于沙子。
4. 狗牌感觉……不是很那个，看看别人怎么想。
5. 关于英文：有可能是你模块/包没选对，虽然我记得所有的attribute是在1.16快照期间更改的。我会尝试复现一下。

**Comment by XxLittleCxX** [comment]
沙砾要改成石乐志的话感觉太牵强了，而且这个梗我不是很喜欢，相比之下石乐还比较好。

狗牌倒没有很反感，中立吧，再看看别人怎么想。

**Comment by zh9c418** [comment]
🐕牌？侮辱狗勾这种勾当我可不敢干
还有那个苹果，你咋不直接改成 苹果(Inc.) 呢？
圆石叫石子**过于牵强，除非上个材质包**
还有，请记住，鹦鹉螺~~不能拿嘴口~~不能吹，但还没出的山羊角我看行（？）

**Comment by zhyf0610** [comment]
额怎么都聚焦到狗牌上了。。。

**Comment by lakejason0** [comment]
> 额怎么都聚焦到狗牌上了。。。

zszz你工作室furry比较多.jpg
这也没有办法。

**Comment by lakejason0** [comment]
现在开始看看这个attribute怎么回事吧……这个真的没注意到。

**Comment by lakejason0** [comment]
> 现在开始看看这个attribute怎么回事吧……这个真的没注意到。可能有必要看看英文源文件是不是又什么申必改动。

明白了。preset_build.py的问题。

**Comment by lakejason0** [comment]
木桶已经统一到一个名字了。

**Comment by lakejason0** [comment]
不明白Wither Skeleton这里有什么Consistency可言。

**Comment by zhyf0610** [comment]
> 
> 
> 不明白Wither Skeleton这里有什么Consistency可言。

煤矿和黑石的翻译均带有非洲字样，击杀凋零骷髅会产出非洲矿石[doge]

**Comment by zhyf0610** [comment]
> 
> 
> 🐕牌？侮辱狗勾这种勾当我可不敢干
> 还有那个苹果，你咋不直接改成 苹果(Inc.) 呢？
> 圆石叫石子**过于牵强，除非上个材质包**
> 还有，请记住，鹦鹉螺~不能拿嘴口~不能吹，但还没出的山羊角我看行（？）

苹果.inc的话建议修改材质包然后名字改成 啃了一口的苹果(inc.)
狗牌是军队身份牌的调侃称呼😂

**Comment by AlPha5130** [comment]
英文的问题已修复。

**Comment by zhyf0610** [comment]
烟花：发射建议改为 窜天猴：发射
![图片](https://user-images.githubusercontent.com/42296671/109387943-1ceb1100-793f-11eb-9e07-ce0b3be15998.png)

**Comment by Dianliang233** [comment]
部分解决，剩余已驳回。

不活跃。若有必要请重新开启（reopen）。
