### ISSUE TITLE
小建议

### ISSUE THREAD

**Issue by FurryLee** [Teahouse-Studios/mcwzh-meme-resourcepack#152]
建议做一个梗体中文pcl2专供版
因为这群里的梗太多了(

**Comment by zh9c418** [comment]
还请你们pcl2**自己**搞一个梗体中文pcl特供，自己开个分支然后去改，再说哪个群里没一两个“壮士”在那里整乐子呢？
希望同志被龙腾猫跃发现了，不要被他夹到。

**Comment by zh9c418** [comment]
还有，替我向龙腾猫跃问个好。
![-4f07a6b24f09c3d9](https://user-images.githubusercontent.com/31580789/109093317-1ef07c80-7753-11eb-8e06-85ad1b118434.png)

**Comment by FurryLee** [comment]
啊这
我还是头一次接触github😂

**Comment by Timicasto** [comment]
> 还有，替我向龙腾猫跃问个好。
> ![-4f07a6b24f09c3d9](https://user-images.githubusercontent.com/31580789/109093317-1ef07c80-7753-11eb-8e06-85ad1b118434.png)

那，我去吧（？

**Comment by zh9c418** [comment]
烦请这位小furry别把这里变成什么聊天软件了，github不是社交媒体( •︠ˍ•︡ )
