### ISSUE TITLE
把“木锄”改成“圈地工具”

### ISSUE THREAD

**Issue by Ironnoob73** [Teahouse-Studios/mcwzh-meme-resourcepack#155]
**你的特性建议和某个问题相关吗？请描述。**
各类服务器都带地皮系统，地皮系统的工具大多（或者说都是）使用的是木锄。

**描述你喜欢的解决方法**
将“木锄”译名改为“圈地工具”(如果能顺便改一下木斧也行......)

**描述你想到的其他解决方案**
等我玩会git我自己来（

**附加信息**
![2021-03-07_11 02 09](https://user-images.githubusercontent.com/67966070/110227568-9af97a00-7f34-11eb-8249-2886b512f98b.png)
_为数不多的几个还没有被安排的物品......好吧实际上还不少......或者我们可以整理一个未更改译名表？_

**Comment by Dianliang233** [comment]
> *为数不多的几个还没有被安排的物品...... 好吧实际上还不少...... 或者我们可以整理一个未更改译名表？*

不是每一个译名都需要有所更改。

**Comment by Ironnoob73** [comment]
> 不是每一个译名都需要有所改变。

行吧......不过如果我准备pull我编写的更改还需要注意什么？

**Comment by lakejason0** [comment]
> > 不是每一个译名都需要有所改变。
> 
> 行吧......不过如果我准备pull我编写的更改还需要注意什么？

你先改再说。

**Comment by lakejason0** [comment]
木斧倒是建议改为“蓝鸡的1/64”
