### ISSUE TITLE
bugs

### ISSUE THREAD

**Issue by LiuQiYu671** [Teahouse-Studios/mcwzh-meme-resourcepack#159]
**描述**
请简明扼要地描述漏洞。
炼药台显示为错误方块，唱片没有被替换
**复现步骤**
复现漏洞的步骤：

1. 前往“...”
2. 点击“...”
3. 滑动至“...”
4. 查看错误

**正常行为**
请简明扼要地描述应该发生的行为。

**截图**
可以的话，加上截图可以帮助解释你的问题。
![2021-03-26_23 51 53](https://user-images.githubusercontent.com/81440821/112682260-d5f32b80-8eaa-11eb-8140-25106703f1d2.png)

**版本**

* 操作系统：[例：Windows]Windows 10
* Minecraft 版本：[例：1.15.2]1.12.2
* 资源包版本：[例：0.1.0]
* 环境 [例：加载了Fabric/Forge，安装了CustomSkinLoader]
加载了Forge
**其他内容**
添加更多关于漏洞的来龙去脉。

**Comment by Dianliang233** [comment]
炼药台：请提供您选中的模块列表。
唱片：请确认是否安装了替换包。若已安装，请先解压再使用。

**Comment by LiuQiYu671** [comment]
Thank U very much！

在 2021-03-27 10:14:04，Dianliang233 ***@***.***> 写道：


炼药台：请提供您选中的模块列表。
唱片：请确认是否安装了替换包。若已安装，请先解压再使用。

**Comment by lakejason0** [comment]
> Thank U very much！ 在 2021-03-27 10:14:04，Dianliang233 ***@***.***> 写道： 炼药台：请提供您选中的模块列表。 唱片：请确认是否安装了替换包。若已安装，请先解压再使用。 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

问题是否已解决？

**Comment by Dianliang233** [comment]
问题似乎已解决。若有更多疑问，请 reopen。

**Comment by LiuQiYu671** [comment]
yeah



在 2021-03-29 21:51:57，"lakejason0" ***@***.***> 写道：

Thank U very much！ 在 2021-03-27 10:14:04，Dianliang233 @.***> 写道： 炼药台：请提供您选中的模块列表。 唱片：请确认是否安装了替换包。若已安装，请先解压再使用。 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

问题是否已解决？
