### ISSUE TITLE
无法看见中文，装好之后还是显示英文

### ISSUE THREAD

**Issue by KLqiqi** [Teahouse-Studios/mcwzh-meme-resourcepack#160]
**描述**
请简明扼要地描述漏洞。

**复现步骤**
复现漏洞的步骤：

1. 前往“...”
2. 点击“...”
3. 滑动至“...”
4. 查看错误

**正常行为**
请简明扼要地描述应该发生的行为。

**截图**
可以的话，加上截图可以帮助解释你的问题。

**版本**

* 操作系统：[例：Windows]
* Minecraft 版本：[例：1.15.2]
* 资源包版本：[例：0.1.0]
* 环境 [例：加载了Fabric/Forge，安装了CustomSkinLoader]

**其他内容**
添加更多关于漏洞的来龙去脉。

**Comment by Dianliang233** [comment]
无法判断错误。请添加版本信息和截图。

will close this in 72hrs

**Comment by Ironnoob73** [comment]
这个问题我遇到过，如果你同时安装了唱片包，请把唱片包放在主包上面，如果没有请尽量让主包最后加载。
