### ISSUE TITLE
支持 IC2Exp、BC 等老牌模组

### ISSUE THREAD

**Issue by UMRnInside** [Teahouse-Studios/mcwzh-meme-resourcepack#162]
**你的特性建议和某个问题相关吗？请描述。**
没有 IC2Exp 和 BC 的梗体中文翻译，我很不爽！

**描述你喜欢的解决方法**
添加这些模组的翻译！

**描述你想到的其他解决方案**
没有。

**附加信息**
* 科技复兴（TR）的翻译已经存在
* 在 mcmod.cn 上，IC2Exp 的人气大于 TR，而二者体量相近
* BC 的体量小于 TR
* ~~我觉得你们在歧视只支持到 1.12.2 的 Mod，但我没有证据~~

**Comment by Dianliang233** [comment]
为什么要关呢？（疑惑

todo

**Comment by UMRnInside** [comment]
> 为什么要关呢？（疑惑
> 
> todo

[list_of_supported_mods.md](https://github.com/Teahouse-Studios/mcwzh-meme-resourcepack/blob/master/list_of_supported_mods.md)
> 由于本资源包使用了自定义的语言代码zh_meme，因此并非所有Mod都支持本语言（其实是几乎所有都不，(╯‵□′)╯︵┻━┻）。如果你想让某个Mod支持梗体中文， 请不要来找我们！

**Comment by Dianliang233** [comment]
BC 已添加。IC2Exp 由于版权协议问题，无法加入。请联系 Mod 作者取得授权。

不活跃。若有必要请重新开启（reopen）。
