### ISSUE TITLE
[ 物品:捡起 ] 修改

### ISSUE THREAD

**Issue by Chinese-Cyq20100313** [Teahouse-Studios/mcwzh-meme-resourcepack#171]
**你的特性建议和某个问题相关吗？请描述。**
[杜比顶级音效] 字幕 里 物品:捡起 少点东西
 
**描述你喜欢的解决方法**
物品:被坏叔叔偷走了

**描述你想到的其他解决方案**
呃啊！数据被吃掉了！
请稍后再试！
**附加信息**
呃啊！数据被吃掉了！
请稍后再试！

**Comment by zh9c418** [comment]
感觉没啥意思🤔

**Comment by zh9c418** [comment]
物品:被~~陈睿~~叔叔顺走了

**Comment by Dianliang233** [comment]
不活跃。若有必要请重新开启（reopen）。
