### ISSUE TITLE
【模组适配】矿物高亮Mod已自行适配梗体中文

### ISSUE THREAD

**Issue by teddyxlandlee** [Teahouse-Studios/mcwzh-meme-resourcepack#173]
源码：https://github.com/Featurehouse/bright-ore  
~~听说 Pigeonia Featurehouse 的模组都支持梗中~~
~~听说烤地瓜的梗中最近咕咕咕了~~

**Comment by lakejason0** [comment]
SPM是什么（懵）
手机中，之后看看。

**Comment by lakejason0** [comment]
repo内已添加，帖子内等待你给出mcbbs的发布贴后完成（手机写bbcode太困难了咕咕咕）。

**Comment by teddyxlandlee** [comment]
@lakejason0 目前除烤地瓜（SPM）外，已有两个 Pigeonia Featurehouse 系模组适配梗体中文：  
- [Wake Up（大梦初醒）](https://www.mcbbs.net/thread-1222714-1-1.html)  
- [Bright Ore（矿物高亮）](https://www.mcbbs.net/thread-1201226-1-1.html)
