### ISSUE TITLE
装完后为啥是英语

### ISSUE THREAD

**Issue by OxoDr-FunoxO** [Teahouse-Studios/mcwzh-meme-resourcepack#174]
**描述**
装完后是英语

**复现步骤**
复现漏洞的步骤：

就正常加载，然后是英文

**正常行为**
我加载了资源包，也选择了语言，但显示的是英语，多次切换也无效

**截图**

**版本**
1.17

* 操作系统：Windows 7
* Minecraft 版本：1.17
* 资源包版本：最新版
* 仅OptiFine

**其他内容**
没

**Comment by lakejason0** [comment]
请提供您的下载途径（如果是通过网页打包下载的请一并提供您在下载界面的相关设置）。提供的信息越多越有利于我们排查。

**Comment by lakejason0** [comment]
若可以的话请把您收到的资源包发送一份，有助于确认资源包打包时可能出现的问题的原因。感谢您的反馈，为您带来的不便我们深表歉意。（不是这语气也太正经了8⃣️）

**Comment by OxoDr-FunoxO** [comment]
就在在线构建上下载的

**Comment by lakejason0** [comment]
> 就在在线构建上下载的

请给出你所选择的选项（或者你什么都没选直接点击了提交构建选项？）

**Comment by OxoDr-FunoxO** [comment]
e..都是全选...没有酿造台模型、作者僵尸和多洛洛狼

**Comment by lakejason0** [comment]
> e..都是全选...没有酿造台模型、作者僵尸和多洛洛狼

hmmm……不太清楚发生了什么。如果可以的话请把你下载到的资源包发送一份到这里。等其他人看到了再看看是不是有什么bug。

**Comment by OxoDr-FunoxO** [comment]
[1.17梗中.zip](https://github.com/Teahouse-Studios/mcwzh-meme-resourcepack/files/6690864/1.17.zip)

**Comment by Ironnoob73** [comment]
我大概知道怎么回事，你是不是装唱片包或者和其他资源包连用了？我记得梗中本体需要放在资源包列表最下面才能生效，这是Minecraft的一个特性。

**Comment by OxoDr-FunoxO** [comment]
我装了唱片包

**Comment by OxoDr-FunoxO** [comment]
这特性有点坑r。。。

**Comment by Dianliang233** [comment]
似乎已解决。

不活跃。若有必要请重新开启（reopen）。
