### ISSUE TITLE
草径显示问题

### ISSUE THREAD

**Issue by Xiaomo250** [Teahouse-Studios/mcwzh-meme-resourcepack#177]
**描述**
草径没有正确显示为中文，而显示为“Grass Path”

**复现步骤**
复现漏洞的步骤：
1.在游戏中使用WAILA指向草径
2.查找梗体中文语言文件,发现“block.minecraft.grass_path"被错误记为"block.minecraft.dirt_path"

**正常行为**
草径应显示为”夯土路“

**截图**
可以的话，加上截图可以帮助解释你的问题。

**版本**

* 操作系统：Windows10
* Minecraft 版本：1.16.5
* 资源包版本：1.4.0
* 环境：原版

**其他内容**
添加更多关于漏洞的来龙去脉。

**Comment by XxLittleCxX** [comment]
![image](https://user-images.githubusercontent.com/26459759/123961332-cec84600-d9e2-11eb-973b-033d42b47c0f.png)

你看看是不是要勾选这个
