### ISSUE TITLE
推荐安装这个资源包之后把Java版的logo改成如图的“jvav版”

### ISSUE THREAD

**Issue by RxinnotRstar** [Teahouse-Studios/mcwzh-meme-resourcepack#179]
![图片](https://user-images.githubusercontent.com/56676566/124387658-018b7a80-dd12-11eb-81c1-409d41bc7b1d.png)

**Comment by Dianliang233** [comment]
涉嫌网暴。

**Comment by RxinnotRstar** [comment]
> 
> 
> 涉嫌网暴。

可还行
左下角的“mojang SB”呢？（滑稽）
