### ISSUE TITLE
加亿点料！

### ISSUE THREAD

**Issue by SNWCreations** [Teahouse-Studios/mcwzh-meme-resourcepack#181]
**你的特性建议和某个问题相关吗？请描述。**
不是。我希望把我的完成作品提供给你们使用。

**描述你喜欢的解决方法**
将本人的 MCBBS版MC 资源包中的相关翻译加入此资源包，届时本人将停止此包的更新。
虽然我这个作品中的翻译已经有其他字符串替代，但是我希望仍有部分好的翻译能被加入。

**附加信息**
MCBBS版MC 资源包仓库地址见 [https://github.com/SNWCreations/mc-mcbbsedition-rspack](https://github.com/SNWCreations/mc-mcbbsedition-rspack)
联系我: MCBBS @ZX夏夜之风

**Comment by lakejason0** [comment]
az，这种要求我们就没见过

**Comment by SNWCreations** [comment]
你可以考虑一下awa，我这个项目没时间更了，我需要更多时间为CPS和我自己工作。
虽然是被某UP做个一次视频的项目，但我的项目太多了，我无力继续更新。

看看有没有合适的翻译，加亿点进去，就完事了

**Comment by Dianliang233** [comment]
可以考虑作为一个模块加入。

**Comment by lakejason0** [comment]
这，你自己的项目丢给别人算是个什么事情啊……
真要合并的话也得等我们自己看看

**Comment by lakejason0** [comment]
嘛倒是可以

**Comment by SNWCreations** [comment]
> 可以考虑作为一个模块加入。

我是这么想的，当然这个项目我早有计划废弃。

**Comment by SNWCreations** [comment]
> 这，你自己的项目丢给别人算是个什么事情啊……
> 真要合并的话也得等我们自己看看

当然可以啦！欢迎康康

**Comment by XxLittleCxX** [comment]
有一些问题

> 当然，这些修改后的名字借鉴于部分 MCBBS (www.mcbbs.net) 的用户。

在文件中放这些名字取得原用户的同意了吗？这些用户和你是好友关系吗

**Comment by XxLittleCxX** [comment]
其中大量出现的`茶馆`有什么含义（

**Comment by SNWCreations** [comment]
> 有一些问题
> 
> > 当然，这些修改后的名字借鉴于部分 MCBBS ([www.mcbbs.net](http://www.mcbbs.net)) 的用户。
> 
> 在文件中放这些名字取得原用户的同意了吗？这些用户和你是好友关系吗

是好友关系，已征得其同意。

**Comment by SNWCreations** [comment]
> 其中大量出现的`茶馆`有什么含义（

就是好玩，不要较真awa

**Comment by XxLittleCxX** [comment]
@Teahouse-Studios/memified-chinese-content-group 征询意见
