### ISSUE TITLE
关于［多人娱乐］界面更改部分文字的建议

### ISSUE THREAD

**Issue by 2845984686** [Teahouse-Studios/mcwzh-meme-resourcepack#188]
**你的特性建议和某个问题相关吗？请描述。**
我在[多人娱乐]（或称［一起来，更精彩］）界面想出了一个新点子。

**描述你喜欢的解决方法**
按钮［我要进去！］文字表述替换成［让我访问！］会更生草。

**描述你想到的其他解决方案**
考虑到此衍生梗“不够出名”（摘自CONTRIBUTING.md），也可替换成［让我康康！］，这样同时满足了“够出名”和“令人生草”（摘自CONTRIBUTING.md）的要求，但比较脱离实际，不能准确表达［加入服务器］的行为。

**附加信息**
“让我访问”词条出处：bilibili.com/BV1rE411T7Gd（最简）（HTTPS）
“让我访问”词条相关解释：jikipedia.com/9491623（非权威）（最简）（HTTPS）
“让我康康”词条出处：bilibili.com/BV1rA411g7q8（最简）（HTTPS）
“让我康康”词条相关解释：jikipedia.com/825944242（非权威）（最简）（HTTPS）
“让我康康”父级词条百科：baike.baidu.com/item/如果早知道男生也会被性侵（权威）（最简）（HTTPS）

**Comment by lakejason0** [comment]
这考据给的让我这个wiki编者望尘莫及啊（远目

**Comment by SkyEye-FAST** [comment]
这考据给的让我这个wiki编者望尘莫及啊（远目

**Comment by Dianliang233** [comment]
让我访问就行了
