### ISSUE TITLE
翻译中的若干错误

### ISSUE THREAD

**Issue by yezhiyi9670** [Teahouse-Studios/mcwzh-meme-resourcepack#190]
**描述**

- [ ] `death.fell.accident.twisting_vines: %1$s从缠怨藤上摔了下来`，“缠怨藤”可以改为“通天藤”，以和方块翻译匹配。
- [ ] ~~`debug.creative_spectator.help: F3 + N = 在上一模式和游魂模式间切换`，“上一模式”应改为“上帝模式”。~~
- [ ] `stat.minecraft.play_one_minute: Time Played` 缺失

**版本**

* 操作系统：[Windows]
* Minecraft 版本：[1.16.5]
* 资源包版本：[Release 1.4.0]
* 环境 [Forge, CustomSkinLoader]

**Comment by lakejason0** [comment]
上一模式是原文

**Comment by lakejason0** [comment]
其他问题可以确认，将会更改
