### ISSUE TITLE
来自 B 站私信的反馈

### ISSUE THREAD

**Issue by Dianliang233** [Teahouse-Studios/mcwzh-meme-resourcepack#191]
![image](https://user-images.githubusercontent.com/45287180/127760172-15a42998-d4c5-42a0-b674-107d5e2170a3.png)
![image](https://user-images.githubusercontent.com/45287180/127760180-eb03e477-3cba-4b60-9a04-1a689740fcdf.png)

**Comment by zh9c418** [comment]
令人血压升高的私信反馈建议不处理(

**Comment by RxinnotRstar** [comment]
谢谢，低血压患者变高血压患者了

我来改吧

**Comment by RxinnotRstar** [comment]
催审.jpg

**Comment by lakejason0** [comment]
没时间

**Comment by Dianliang233** [comment]
不活跃。若有必要请重新开启（reopen）。
