### ISSUE TITLE
可以添加对 I18n汉化资源包的 支持嘛

### ISSUE THREAD

**Issue by OcrSu** [Teahouse-Studios/mcwzh-meme-resourcepack#193]
有一些模组需要 汉化资源包才能显示中文
但是用了梗体中文的“天朝”语言选项后无法正常使用 汉化资源包
望能支持
![QQ图片20210815060104](https://user-images.githubusercontent.com/75876201/129461153-d958a259-39de-4234-8034-bd0c2b8e0662.png)
![QQ图片20210815060209](https://user-images.githubusercontent.com/75876201/129461174-b0d5285b-a545-4979-8435-c819a4d56649.png)
![QQ图片20210815060211](https://user-images.githubusercontent.com/75876201/129461177-72d7a2cb-3ecb-4ed0-b69d-a52b527729f2.png)
![QQ图片20210815060214](https://user-images.githubusercontent.com/75876201/129461178-4a43930d-b882-4514-be8b-8ad61199a3d5.png)
https://github.com/CFPAOrg/Minecraft-Mod-Language-Package

**Comment by lakejason0** [comment]
与Mod内容搭配请选择`compatible`版本的梗体中文。

**Comment by OcrSu** [comment]
> 与Mod内容搭配请选择`compatible`版本的梗体中文。

我在在线构建中，选择了mod内容选择中的“所有”，但貌似不是compatible
我如何在 在线构建 中 选择 compatible 版本呢？

**Comment by lakejason0** [comment]
此问题已汇报给在线构建相关人员，请等待回复。

**Comment by lakejason0** [comment]
另，在Releases中有`compatible`版本。可以先测试一下行不行。

**Comment by OcrSu** [comment]
> 另，在Releases中有`compatible`版本。可以先测试一下行不行。

Releases中的compatible 版本可以正常兼容汉化资源包
期待在线构建的修复！

**Comment by lakejason0** [comment]
似乎是功能的意外移除。

**Comment by Dianliang233** [comment]
已经重新加入。

**Comment by Dianliang233** [comment]
或者我们可以直接把[资源包](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/tree/main)套过来……但是有协议不兼容的问题

**Comment by OcrSu** [comment]
好，谢谢！
