### ISSUE TITLE
模块集合中的冲突项处理

### ISSUE THREAD

**Issue by LCG1280** [Teahouse-Studios/mcwzh-meme-resourcepack#194]
![QQ截图20210711211649](https://user-images.githubusercontent.com/73746445/125196739-7e2bd500-e28d-11eb-8f19-57d714c3bff5.png)

**Comment by zh9c418** [comment]
Firefox截图功能有一次性截取整个页面（
https://support.mozilla.org/zh-CN/kb/firefox%20%E6%88%AA%E5%9B%BE

**Comment by AlPha5130** [comment]
长期无回复的issue，如有进展请重开一个。
