### ISSUE TITLE
草径方块未翻译

### ISSUE THREAD

**Issue by zhyf0610** [Teahouse-Studios/mcwzh-meme-resourcepack#196]
**描述**
请简明扼要地描述漏洞。

草径没有翻译，当然如果我不了解这个梗的话在此致歉

**截图**
可以的话，加上截图可以帮助解释你的问题。
![2021-08-29_07 26 41](https://user-images.githubusercontent.com/42296671/131233458-10efd03b-b8bf-4a87-a3d8-d92e8378a620.png)

**版本**

* 操作系统：Windows 10 21H1
* Minecraft 版本：1.17.1
* 资源包版本：1.4.1
* 环境 无mod与modloader，但是选择了很多构建选项

**Comment by SkyEye-FAST** [comment]
无法复现，请详细描述你选择的构建选项。

1.16.5以后的版本中“草径”（Grass Path）已被改为“土径”（Dirt Path）：
>     "block.minecraft.dirt_path": "土径",

如果你选择了这个语言模块（lang_grass_path_1.12.2-1.16.5），请将其取消选择。
![image](https://user-images.githubusercontent.com/61134881/131236716-0aede874-a505-4fac-a5c1-8cef86715bdc.png)

**Comment by zhyf0610** [comment]
问题解决

**Comment by SkyEye-FAST** [comment]
请问还有什么问题吗？

**Comment by zhyf0610** [comment]
![图片](https://user-images.githubusercontent.com/42296671/131492044-b828c6d1-2ff4-4f17-86e9-550c3b06ca45.png)
![图片](https://user-images.githubusercontent.com/42296671/131492065-736b3cc8-52ec-4a7f-b4f3-cf5c5a6622b9.png)
![图片](https://user-images.githubusercontent.com/42296671/131492081-5352d608-afeb-41de-ac74-d342b4c37319.png)
![图片](https://user-images.githubusercontent.com/42296671/131492106-b7d209f4-52b7-4d62-8d02-4d6c322fd3f6.png)
![图片](https://user-images.githubusercontent.com/42296671/131492121-cd68c942-bc35-4aa8-8588-5d978311a6b9.png)
![图片](https://user-images.githubusercontent.com/42296671/131492138-9391968d-c366-4ae0-9371-5ec81e2bee81.png)
![图片](https://user-images.githubusercontent.com/42296671/131492159-0f619583-28f9-41de-8bf6-c4d480b49ac3.png)
![图片](https://user-images.githubusercontent.com/42296671/131492177-f7853305-31c4-41af-960f-240ee127f87c.png)
![图片](https://user-images.githubusercontent.com/42296671/131492188-862de4f4-31c3-4928-9b1e-7571167e79f5.png)
![图片](https://user-images.githubusercontent.com/42296671/131492220-89104ab2-2093-4a02-8a58-d0e919d9c498.png)
![图片](https://user-images.githubusercontent.com/42296671/131492242-0cc4848d-c74f-426c-b2aa-a7312ea7f3f7.png)
在关闭兼容选项后仍然存在问题

**Comment by zhyf0610** [comment]
![2021-08-31_19 09 01](https://user-images.githubusercontent.com/42296671/131492396-234b0b96-3fe5-42b7-80d5-5c09f36c4fa8.png)

**Comment by zhyf0610** [comment]
如果启用兼容选项则翻译为土径，后缀为ba9d4df

**Comment by SkyEye-FAST** [comment]
> 如果启用兼容选项则翻译为土径，后缀为ba9d4df

请通过分享向我们提供您的构建选项。
![image](https://user-images.githubusercontent.com/61134881/131492828-05d4609d-63f6-45b8-8c41-0d715a7d3f9b.png)

**Comment by zhyf0610** [comment]
[https://meme.wd-ljt.com/?type=je&ver=1&input=%7B%22modOption%22%3A%22all%22%2C%22compatible%22%3Afalse%2C%22mod%22%3A%5B%5D%2C%22resource%22%3A%5B%22red_leaf_valley%22%2C%22open_close_sound%22%2C%22famous_scene%22%2C%22disco_ball%22%2C%22annoying_sounds%22%2C%22bell_sound%22%2C%22first_anniversary%22%2C%22baguette%22%2C%22vulpes_ferrilata%22%2C%22BUGJUMP%22%2C%22jinkela%22%2C%22fursuit%22%2C%22real_grass%22%2C%22blue_tube_poster%22%2C%22minecart_helmet%22%2C%22latiao%22%2C%22brewing_stand_model%22%2C%22author_zombies%22%2C%22strange_meme_background%22%2C%22questioning_totem%22%2C%22mopemope%22%2C%22rainbow_enchanting%22%2C%22bee_pickaxe%22%2C%22dorowolf_texture%22%5D%2C%22language%22%3A%5B%5D%2C%22collection%22%3A%5B%22choice_modules_1%22%5D%2C%22child%22%3A2%7D&inputBasic=%7B%22format%22%3A7%7D](url)

**Comment by zhyf0610** [comment]
[ba9d4df.txt](https://github.com/Teahouse-Studios/mcwzh-meme-resourcepack/files/7083442/ba9d4df.txt)

**Comment by SkyEye-FAST** [comment]
![image](https://user-images.githubusercontent.com/61134881/131493594-c7b75488-3207-4ff7-b349-675f11fc49e3.png)
这里仍然是草径 `grass_path` 。

**Comment by zhyf0610** [comment]
所以这个是bug哈？

**Comment by SkyEye-FAST** [comment]
> 所以这个是bug哈？

我们正在排查……导致打包错误的原因尚未可知。总之是打包出了这样一行缝合的键名和字符串：

`"block.minecraft.grass_path": "夯土路",`

**Comment by AlPha5130** [comment]
长期无回复的issue，如有进展请重开一个。

**Comment by AlPha5130** [comment]
已无法复现。
