### ISSUE TITLE
求添加HomoOS Sans Font

### ISSUE THREAD

**Issue by 8MiYile** [Teahouse-Studios/mcwzh-meme-resourcepack#197]
**你的特性建议和某个问题相关吗？请描述。**
梗材质内缺少梗系字体

**描述你喜欢的解决方法**
https://www.mcbbs.net/thread-1260266-1-1.html
在选项内添加这个包即可

**描述你想到的其他解决方案**

**附加信息**
就字体包

**Comment by 8MiYile** [comment]
算了我自己来 #198

**Comment by Dianliang233** [comment]
我不懂，为什么这个字体就是梗了？有什么必要吗？

**Comment by Dianliang233** [comment]
根据讨论，我们认为此模块没有必要。Closing
