### ISSUE TITLE
关于繁体

### ISSUE THREAD

**Issue by lakejason0** [Teahouse-Studios/mcwzh-meme-resourcepack#20]
**你的特性建议和某个问题相关吗？请描述**
这个资源包似乎没有提供繁体。考虑到MCWZH存在使用繁体中文的用户，是否应该也提供一份繁体的？

**描述你喜欢的解决方法**
Another branch called “~~哏體中文~~ㄍㄥˇ體中文”.

**存在的问题**
* 没有人动工。
* 地区差异较大。
* 工作量++

**附加信息**
此问题应该会被长期搁置。如果有意向加入，欢迎PR。

**Comment by RxinnotRstar** [comment]
个人认为，梗体中文的受众群体使用的语言基本上是简体中文，所以制作”ㄍㄥˇ體中文“的需求可能不是很大。
我本来想试一下来着，但是想了想还是算了。
其实是因为我也不怎么懂繁体中文（

**Comment by lakejason0** [comment]
> 个人认为，梗体中文的受众群体使用的语言基本上是简体中文，所以制作”ㄍㄥˇ體中文“的需求可能不是很大。
> 我本来想试一下来着，但是想了想还是算了。
> 其实是因为我也不怎么懂繁体中文（

所以我说了有人愿意做可以做，梗的地域差异性还是很大的。

**Comment by Ironnoob73** [comment]
能找到使用繁中的朋友就会简单很多

**Comment by lakejason0** [comment]
话是这么说，但是有别的困难

**Comment by lakejason0** [comment]
先别回复了，本来也没打算做
