### ISSUE TITLE
词条建议

### ISSUE THREAD

**Issue by 8MiYile** [Teahouse-Studios/mcwzh-meme-resourcepack#201]
**你的特性建议和某个问题相关吗？请描述。**
突然觉得 FL Studio 的那个图标 可以覆盖Minecraft原版的胡萝卜 然后可以改名成 FL Studio

**描述你喜欢的解决方法**
如上

**Comment by Ironnoob73** [comment]
可以做成一个模块

**Comment by Dianliang233** [comment]
![image](https://user-images.githubusercontent.com/45287180/133112669-2752a50d-0bce-4615-a0a1-858f0d16d6fd.png)
我不理解，这难道不是芒果吗，为什么会幻视成胡萝卜

**Comment by lakejason0** [comment]
这为什么是芒果，为什么不能说（略

**Comment by Dianliang233** [comment]
官设：芒果+草莓

**Comment by zh9c418** [comment]
FL图标不是你说用就能用

**Comment by AlPha5130** [comment]
长期无回复的issue，如有进展请重开一个。

**Comment by DoroWolf** [comment]
不会修复：copyright
