### ISSUE TITLE
又一些新点子（物品和死亡信息译名修改）

### ISSUE THREAD

**Issue by Ba-Bao-zhou** [Teahouse-Studios/mcwzh-meme-resourcepack#217]
更改一些译名

**更改前**
→更改后

**马：啊我死了**
→马：飞了

**方解石（凯尔希）**
→棉花化石
→硬化面团
→见光死云朵

**铁锹（铁锨）**
→[你知道吗]一战时这可是一战时堑壕战杀人最多的武器
→胡桃的称手兵器

**bbz_233被滴水石锥扎死了**
→bbz_233：岩石的重量，令人安息

**鸡腿攻击**
→斩尽牛杂

**金苹果（黄油苹果）**
→应急食品

**注释**
应急食品是派蒙的外号，而且很符合物品定位
刻晴的大招攻速快但是很刮（鸡腿攻击）乳刻言论
“岩石的重量，令人安息”是 原神：诺艾尔发动元素战技“护心铠”时语音“岩石的重量，令人安心”的空耳
学园孤岛：惠飞须泽胡桃打“那些家伙”时用的就是铁铲
方解石的贴图看起来像棉花，而且不看方解石的英文的话，完全不知道它和凯尔希有什么联系 
s马=*飞*马（参考“YMFM”和“蛋：飞了”）

**Comment by Ba-Bao-zhou** [comment]
**奶桶**
每天一桶奶，强壮方块人
？毕竟能挤奶的不只有牛了

*流浪商人：喝奶*
→流浪奸商：Let's 牛乳 dance
？翻译还是有点问题

**Comment by zh9c418** [comment]
游戏里能显示emoji?

**Comment by xtexChooser** [comment]
.link

**Comment by MoupiPics** [comment]
推荐1.19把山羊角音效改这个https://www.youtube.com/watch?v=UaUa_0qPPgc
也可以当做袭击的号角

**Comment by DoroWolf** [comment]
> 推荐1.19把山羊角音效改这个https://www.youtube.com/watch?v=UaUa_0qPPgc 也可以当做袭击的号角

请另开issue

**Comment by Ba-Bao-zhou** [comment]
> 推荐1.19把山羊角音效改这个https://www.youtube.com/watch?v=UaUa_0qPPgc 也可以当做袭击的号角
把Dream号角换成烧开水的声音（

**Comment by Ba-Bao-zhou** [comment]
> 推荐1.19把山羊角音效改这个https://www.youtube.com/watch?v=UaUa_0qPPgc 也可以当做袭击的号角

把Dream号角换成烧开水的声音（
