### ISSUE TITLE
JAVA版本的唱片包不能下载了

### ISSUE THREAD

**Issue by Kintakumi** [Teahouse-Studios/mcwzh-meme-resourcepack#218]
**描述**
JAVA版本的唱片包不能下载了
以下是错误页面的内容

This XML file does not appear to have any style information associated with it. The document tree is shown below.
<Error>
<Code>InvalidObjectState</Code>
<Message>The operation is not valid for the object's state</Message>
<RequestId>61B35019375B533639E91505</RequestId>
<HostId>pro-xhb-video.oss-cn-hangzhou.aliyuncs.com</HostId>
<ObjectName>dse/18479c9e-7a70-4785-9aa5-7ee058b3e4cf.zip</ObjectName>
</Error>

**Comment by Dianliang233** [comment]
@XxLittleCxX 是否是晓黑板不能再使用？

**Comment by XxLittleCxX** [comment]
已更新
