### ISSUE TITLE
唱片包问题

### ISSUE THREAD

**Issue by LCG1280** [Teahouse-Studios/mcwzh-meme-resourcepack#221]
版本 1.11.2
点击唱片包选项，下载材质包后，在游戏中不可用，没有声音。
![图片](https://user-images.githubusercontent.com/73746445/151664808-e0cf8e0d-e900-45fe-9a81-a6c576143032.png)
此时播放没有声音
![图片](https://user-images.githubusercontent.com/73746445/151664853-566d4ad3-085c-4421-982b-f4f91f0ede6f.png)
列表显示

**Comment by Dianliang233** [comment]
并不支持 1.13- 吧

但是可以考虑一下
