### ISSUE TITLE
[style] update repository link

### ISSUE THREAD

**Issue by xtexChooser** [Teahouse-Studios/mcwzh-meme-resourcepack#223]
The link of this repository is still [https://dl.meme.teahou.se/](https://dl.meme.teahou.se/), but it should be [https://meme.wd-ljt.com/](https://meme.wd-ljt.com/)
![image](https://user-images.githubusercontent.com/46394906/153609715-289b8697-d9ed-45b6-adec-9faacbd10d55.png)

**Comment by SkyEye-FAST** [comment]
WAI
