### ISSUE TITLE
铁护腿贴图更改

### ISSUE THREAD

**Issue by SYW-JS** [Teahouse-Studios/mcwzh-meme-resourcepack#225]
**你的特性建议和某个问题相关吗？请描述。**
简明扼要地描述问题所在。例：我在[...]的时候很不爽。
> 并没有不爽....

**描述你喜欢的解决方法**
简明扼要地描述你想要的东西。
> ***把铁护腿的贴图改成倒过来的炼药锅***（二者合成方式颠倒）（灵感来源于舞秋风海底生存）

**描述你想到的其他解决方案**
简明扼要地描述你考虑到的的其他建议、解决方法或特性。

**附加信息**
可以在此加上事情的来龙去脉或者关于这个特性建议的截图。

**Comment by Dianliang233** [comment]
并不行。。。

炼药锅和铁护腿配方是反的，但是都是一个形状
```
---
| |
| |
```

**Comment by DrLee-lihr** [comment]
改物品贴图大概可以，但是穿上之后怎么办

炼药锅又不能像矿车扣在头上一样穿在腿上（

**Comment by DoroWolf** [comment]
只能说 很难实现
