### ISSUE TITLE
梗体中文加载后语言是英语

### ISSUE THREAD

**Issue by parker4096** [Teahouse-Studios/mcwzh-meme-resourcepack#227]
**描述**
语言选择梗体中文后加载的是英语。

**复现步骤**
复现漏洞的步骤：

1. 加载梗体中文资源包
2. 语言选项中选择梗体中文

**正常行为**
梗体中文正常加载。

**截图**
![Minecraft Screenshot 2022 02 28 - 00 50 24 85](https://user-images.githubusercontent.com/75427140/155891540-16f996df-4b93-43ff-b3ae-05d458f953af.png)
![Minecraft Screenshot 2022 02 28 - 00 50 28 75](https://user-images.githubusercontent.com/75427140/155891545-91f12aeb-0ef9-47b9-b0b2-80601554630f.png)
![Minecraft Screenshot 2022 02 28 - 00 54 28 34](https://user-images.githubusercontent.com/75427140/155891694-717bcb51-ecfe-493f-b9ae-11f490dd1970.png)

**版本**

* 操作系统：Windows 11
* Minecraft 版本：1.18.1
* 资源包版本：1.5.0
* 环境：原版

**其他内容**
[mcwzh-meme.8e25a2b.zip](https://github.com/Teahouse-Studios/mcwzh-meme-resourcepack/files/8149044/mcwzh-meme.8e25a2b.zip)
[mcwzh-meme.b097d2e.zip](https://github.com/Teahouse-Studios/mcwzh-meme-resourcepack/files/8149046/mcwzh-meme.b097d2e.zip)

**Comment by XxLittleCxX** [comment]
是使用在线构建导出的吗

是的话右上角 服务器切换 选择 ts 后试试

**Comment by parker4096** [comment]
解决了，谢谢（除了提示是旧版本资源包以外没什么问题）
