### ISSUE TITLE
[feat] mod support(SCP: Sharp)

### ISSUE THREAD

**Issue by xtexChooser** [Teahouse-Studios/mcwzh-meme-resourcepack#228]
[SCP: Sharp](https://github.com/xtexChooser/scp-sharp)是一个关于SCP基金会的MC模组，以LGPL-3.0协议发布。

模组本体现已包含对梗体中文的支持。

请求添加到mod兼容列表中。

（梗中已经被我们塞进README了

**Comment by Dianliang233** [comment]
懒，你发个 pr 吧

**Comment by xtexChooser** [comment]
done in PR #229

**Comment by Dianliang233** [comment]
merged
