### ISSUE TITLE
打开，打开，一定要打开！！！

### ISSUE THREAD

**Issue by gdyxjs** [Teahouse-Studios/mcwzh-meme-resourcepack#233]
**描述**
连接不上服务器

**复现步骤**
1.打开网站
2.报错
3.报错
4.报错
……

**正常行为**
一打开直接报错

**截图**
![image](https://user-images.githubusercontent.com/97278930/159151622-ee28832d-1af1-46be-a8cc-303515462f19.png)

**版本**
* 操作系统：Windows

**其他内容**
无法加载……?¿?¿?¿

**Comment by XxLittleCxX** [comment]
经过测试，打开没有问题，请尝试更换浏览器和网络环境
