### ISSUE TITLE
让语言列表适于在视频中展示的方法

### ISSUE THREAD

**Issue by Ironnoob73** [Teahouse-Studios/mcwzh-meme-resourcepack#240]
**问题**
我注意到几乎所有关于该包的介绍视频不展示语言列表，由于众所周知的原因，即便展示也需要将语言地区那一栏打码。通过修改资源包可以让地区那一栏适于展示，但使用起来并不方便。

**解决方法**
只需在pack.mcmeta中修改以下字段，并将资源包置于原版资源包之后加载即可。
```
{
...
  "language": {
    "zh_meme": {
      "name": "§e梗体中文§r",
      "region": "§c天朝§r",
      "bidirectional": false
    },
    "zh_cn": {
        "name": "简体中文",
        "region": "中国大陆",
        "bidirectional": false
    },
    "zh_tw": {
        "name": "繁體中文",
        "region": "中國台灣",
        "bidirectional": false
    },
    "zh_hk": {
        "name": "繁體中文",
        "region": "中國香港",
        "bidirectional": false
    }
  },
...
}
```
但很明显，这将导致资源包本来的很多功能失效。

**其他解决方案**
可以单独建立一个修复包，与主包分离加载。

**附加信息**
直接修改lang文件或修改了pack.mcmeta但置于原版资源包之前都无法修改语言名称及地区。
可能你会说，这应该作为语言问题反馈给mojang或在crowdin提出，但由于https://crowdin.com/project/minecraft/discussions/2036
以及mojang的态度，同时我也无法找到另一个更加适合提出此建议的地方。如果有更适合讨论此问题的地方，请告诉我，谢谢！

**Comment by Dianliang233** [comment]
blame iso
