### ISSUE TITLE
桶装蝌蚪初音未来化

### ISSUE THREAD

**Issue by GeForceLegend** [Teahouse-Studios/mcwzh-meme-resourcepack#252]
**你的特性建议和某个问题相关吗？请描述。**
将桶装蝌蚪的纹理改绘使其内容物更像初音未来

**描述你喜欢的解决方法**
如图（图源MCBBS V4交流群）
![20220616003805](https://user-images.githubusercontent.com/41003546/173880503-cc0ade31-58e7-4df8-915b-6a9c11cb8f36.jpg)

**Comment by DoroWolf** [comment]
已经整上了
