### ISSUE TITLE
totem_model模块皮肤纹理加载失败，brewing_stand_model模块模型、皮肤纹理加载失败

### ISSUE THREAD

**Issue by xtexChooser** [Teahouse-Studios/mcwzh-meme-resourcepack#269]
1.19.3 香草，进游戏后皮肤是紫黑块

```
[12:30:35] [Worker-Main-6/WARN]: Missing textures in model minecraft:totem_of_undying#inventory:
    minecraft:textures/atlas/blocks.png:mcwzhmeme:entity/dianliang
    minecraft:textures/atlas/blocks.png:mcwzhmeme:entity/gu_zt
    minecraft:textures/atlas/blocks.png:mcwzhmeme:entity/lakejason
    minecraft:textures/atlas/blocks.png:mcwzhmeme:entity/littlec
    minecraft:textures/atlas/blocks.png:mcwzhmeme:entity/lxazl5770
    minecraft:textures/atlas/blocks.png:mcwzhmeme:entity/mysticnebula70
    minecraft:textures/atlas/blocks.png:mcwzhmeme:entity/skyeyefast
    minecraft:textures/atlas/blocks.png:minecraft:entity/wolf/wolf
```

[WebBuilder](https://meme.teahouse.team/#br=GyoCIJwHdqxmOsJks2fHbMw27czLWdiIfmSz6Ih0bZEtmZjJItN3eXoRi1asrmNP+hRoYw0LPM+rTscGQw8vNSssNqn/Vr+LGlEXlGovS6wmkGWCPkM0UB1xGSCbRUpYAwsuOR+874TeCJxNJT6nzJA/sQ+3Nuim5aGCmntu6C0Pn+04hMcBxjoslBNZOWIX9sJe0tSdKvR3ZnilRSwPOFV7IOs2kHP0p6s/d/t957YpIXYiHazK7HnJwthnt3vmfaQ6+VYQheBtMEVJZDQuI8GUHiyszwanN9gzs3RiY9uRuHzwshB8Ko536s5kFqa34p0D76S0E+70jQ/AHVz/BJm7NKw6oDGxtAa5mT7u/uztY8sjbEZ1tdjjPbUzPXvw1tZhjnBHMTGhux+UQcVc2+P96n4=)

[Artifact](https://meme-assets.wd-api.com/meme.teahouse.team-373df2.zip)

**Comment by Gu-ZT** [comment]
问题来源于Mojang对资源包的优化性更改：
* 为改进加载性能，方块与物品的纹理现在会在被方块和物品模型处理前加载。
  * 默认情况下，不在textures/item和textures/block目录中的纹理不会被自动识别，不会被加载。
