### ISSUE TITLE
加入Saturn of Undying

### ISSUE THREAD

**Issue by QWERTY770** [Teahouse-Studios/mcwzh-meme-resourcepack#271]
如题，这个建议我在mcw茶馆群提到过一次，但当时没有人回复，因此在这里发一个issue。

我的Java版玩家名是UndyingSaturn33，玩服务器的时候受到teddyxlandlee的启发（这位经常将不死图腾称为不死土星），于是我制作了一个资源包，将totem of undying改成了saturn of undying，相关纹理和进度名称也一并更改。

但是，我不太了解梗体中文的模块化，不知道如何将自己的资源包作为模块加入进去。请帮我把下面的更改内容写成模块：

以下是资源包做出的更改
**minecraft/lang/zh_meme.json**
```
"advancements.adventure.totem_of_undying.description": "利用不死土星逃离失败神",
"item.minecraft.totem_of_undying": "不死土星"
```
**minecraft/textures/item/totem_of_undying.png**
![totem_of_undying](https://user-images.githubusercontent.com/67259129/213835075-897791eb-a4cb-4aee-a33b-5e8e965aba0c.png)

**Comment by teddyxlandlee** [comment]
《失败神》又一个`lang_sfc`受害者

彳亍口巴，这玩意要不要跟“免费回家”拆开成2个模块？

**Comment by Dianliang233** [comment]
由于上述原因不接受
