### ISSUE TITLE
提点Splash

### ISSUE THREAD

**Issue by W2D3F1X2** [Teahouse-Studios/mcwzh-meme-resourcepack#289]
Not VANILLA!
* 梗图。
![](https://github.com/Teahouse-Studios/mcwzh-meme-resourcepack/assets/117023186/6d6ee264-1d8e-4630-a967-38909d25821d)![](https://github.com/Teahouse-Studios/mcwzh-meme-resourcepack/assets/117023186/465a4fff-58db-464e-a5e7-d05897f307bc)

Too VANILLA!
* 梗图。
![](https://github.com/Teahouse-Studios/mcwzh-meme-resourcepack/assets/117023186/d4d66d93-2e87-460a-b0b5-0b90e8abd4a6)

《逃离出生点》今晚上映
* 出自[https://t.bilibili.com/486380891384860913](https://t.bilibili.com/486380891384860913)。

腐竹切生存啊
* 出自CNR服务器虚假宣传事件。

Also try Bedrock Edition!

如何评价?

我只能说，我能说的

有没有一种可能?

你现在不能游荡，附近有怪物在睡觉

你他娘的还真是个人材

**Comment by DoroWolf** [comment]
大部分已采纳
