### ISSUE TITLE
一些漏洞

### ISSUE THREAD

**Issue by HongShiYH** [Teahouse-Studios/mcwzh-meme-resourcepack#293]
梗体中文现存字符串异常，纹理缺失（如彩虹附魔缺失）等现象，望立即修复
见吃吃喝喝一栏药水处，不死图腾手办纹理
以及设置界面

可能还有很多类似这样的问题

**Comment by HongShiYH** [comment]
![QQ截图20231003200757](https://github.com/Teahouse-Studios/mcwzh-meme-resourcepack/assets/108872851/278088cb-2056-48fa-b4c3-fc33b7d97777)
![QQ截图20231003200827](https://github.com/Teahouse-Studios/mcwzh-meme-resourcepack/assets/108872851/39de3f5f-9ef9-4d02-8ec9-033d3d34add7)
![QQ截图20231003200841](https://github.com/Teahouse-Studios/mcwzh-meme-resourcepack/assets/108872851/5f59ce67-97f9-4dc5-959b-6dc57989a81a)

**Comment by Don-Trueno** [comment]
药水不再有附魔光效这点并不是梗中资源包的问题，而是 Minecraft 从1.19.4-pre1开始就移除了这一特性

**Comment by HongShiYH** [comment]
> 药水不再有附魔光效这点并不是梗中资源包的问题，而是 Minecraft 从1.19.4-pre1开始就移除了这一特性
但附魔书没有彩虹了
![QQ截图20231004111114](https://github.com/Teahouse-Studios/mcwzh-meme-resourcepack/assets/108872851/49b7e1a8-c6c5-4b1f-a1f8-e979dc830c0f)

**Comment by Don-Trueno** [comment]
- 药水不再显示附魔光效的情况已说明，无法仅通过资源包的手段修复。
- 附魔物品也不显示光效是23w04a快照更新将资源包里相关文件改名了，已作出调整。
-  图腾手办显示紫黑块问题已修复。（ #295 ）
- 部分字符串缺失梗化的问题请等待。

**Comment by HongShiYH** [comment]
好的，另请尽快修复梗化缺失问题，谢谢。
