### ISSUE TITLE
更改一些文本的建议

### ISSUE THREAD

**Issue by HongShiYH** [Teahouse-Studios/mcwzh-meme-resourcepack#294]
将被打入虚空的那一段改成
%1$s：%2$s我跟你没完你给我等着！你等着！！！
溺亡改成
%1$s成为了溺尸的一员
你TM劈我瓜是吧--你他妈劈我瓜是吧（18+）
装B被雷劈--装逼被雷劈（18+）
被不为人知的魔法杀死了--死的不明不白
被哐当砸扁了--被哐当砸成了肉泥
%1$s在与%2$s战斗时被掉落的哐当砸扁了--%2$s吃着美味的%1$s肉泥 Ψ(￣∀￣)Ψ
登入中--检票中
加入世界中--挤入世界中
进服记得要加密--正在进行正版验证
门：抖抖抖--门：救命啊！！
门：啊我烂了--门：不要啊！啊啊！！
返回--我走了哈
继续--前进
加载地形中--走你┏ (゜ω゜)=☞
多人游戏--矿工茶馆
购买Realms--为墙外茶馆氪金
开始游戏--进入墙外茶馆
配置Realms--配置墙外茶馆
续期--我要继续在墙外茶馆里嗨
逊出墙外茶馆与添加墙外茶馆
生存的描述
收集资源，与贵物战斗，死一次再一次，打败龙即可胜利。
创造的描述
你就是上帝，你可以为所欲为。
硬核的描述
真男人就来玩
%1$s:AWSL--%1$s：我踏马（18+为我他妈）
链接已关掉--电线被掐了
被服务器中断连接--你太坏了，被茶馆轰出去了
你已被踹出游戏--滚(ノ｀Д)ノ
数据流终止--肥水不流外人田
由于超出封包速率限制而被踢出游戏--由于超出封包速率限制而被踹出茶馆
忽略状态请求--抱歉茶馆暂不受理
登入失败--检票失败
你已被禁止进行多人游戏--哎呦，你太坏了，Bugjump都不让你玩了(ノ｀Д)ノ
未知的主机--你自己不妨看看你连的什么
连接超时--你家网有问题啊
服务器可能发霉了--茶馆长蘑菇了
钟乳石--厚乳石

**Comment by teddyxlandlee** [comment]
部分内容与`mcbbs`模块冲突，该模块包含茶馆相关内容。

连接超时这个改不了，系统字符串。

其他的吧，请你再筛选一下，并且逐条给出修改字符串的必要性。

**Comment by HongShiYH** [comment]
> 部分内容与`mcbbs`模块冲突，该模块包含茶馆相关内容。
> 
> 连接超时这个改不了，系统字符串。
> 
> 其他的吧，请你再筛选一下，并且逐条给出修改字符串的必要性。

与MCBBS模块冲突的直接加入MCBBS模块，另外我再筛选筛选

**Comment by HongShiYH** [comment]
> 部分内容与`mcbbs`模块冲突，该模块包含茶馆相关内容。
> 
> 连接超时这个改不了，系统字符串。
> 
> 其他的吧，请你再筛选一下，并且逐条给出修改字符串的必要性。

将与MCBBS冲突的字符串并入MCBBS模块，剩下的我会单独创一个模块

**Comment by HongShiYH** [comment]
> 部分内容与`mcbbs`模块冲突，该模块包含茶馆相关内容。
> 
> 连接超时这个改不了，系统字符串。
> 
> 其他的吧，请你再筛选一下，并且逐条给出修改字符串的必要性。


%1$s与%2$s不共戴天--%1$s：%2$s我跟你没完你给我等着！你等着！！！
%1$s与水融为了一体--%1$s成为了溺尸的一员
被不为人知的魔法杀死了--死的不明不白
登入中--检票中
加入世界中--挤入世界中
进服记得要加密--正在进行正版验证
门：抖抖抖--门：救命啊！！
门：啊我烂了--门：不要啊！啊啊！！
返回--我走了哈
继续--前进
加载地形中--走你┏ (゜ω゜)=☞
链接已关掉--电线被掐了
被服务器中断连接--你太坏了，被服轰出去了
你已被踹出游戏--滚(ノ｀Д)ノ
数据流终止--肥水不流外人田
登入失败--检票未通过
你已被禁止进行多人游戏--哎呦，你可真够坏的，Bugjump都不让你玩了(ノ｀Д)ノ
服务器可能发霉了--对方长蘑菇了
钟乳石--厚乳石
%1$s步入了虚空之地--%1$s：啊啊啊啊啊啊啊啊（逐步缩小的声音）~
超平坦--大 草 坪
去掉了关于MCBBS的相关内容，也更改了一些东西，这些你看下，没必要的就不加了。

**Comment by Don-Trueno** [comment]
细看了一下：
- 部分字符串已经被玩过梗了，这样的字符串一般不做改动，除非新梗足够有趣。
- 请注意：梗体中文可以适度玩梗，但不可以无限制爆粗。
综上，不予通过。
