### ISSUE TITLE
构筑网站问题

### ISSUE THREAD

**Issue by Mintice12** [Teahouse-Studios/mcwzh-meme-resourcepack#314]
![memebug](https://github.com/Teahouse-Studios/mcwzh-meme-resourcepack/assets/166700016/77f17400-f1bc-4e08-afbc-4729aa5d67bc)
无法下载资源包，请求解决此问题，谢谢

**Comment by Misaka2298** [comment]
![image](https://github.com/Teahouse-Studios/mcwzh-meme-resourcepack/assets/99007518/b25a95cd-8390-4c16-a785-0369a2d122e4)
同上

**Comment by lakejason0** [comment]
可复现，正在询问

**Comment by lakejason0** [comment]
考虑是DNS寄了，等待修复

**Comment by Mintice12** [comment]
已经OK了
