### ISSUE TITLE
Mod内容增加

### ISSUE THREAD

**Issue by Dianliang233** [Teahouse-Studios/mcwzh-meme-resourcepack#45]
**你的特性建议和某个问题相关吗？请描述。**
不。

**描述你喜欢的解决方法**
目前梗体只含有原版游戏，没有mod的内容，在加载mod时看起来很不和谐。
应该增加一个mod支持。

但是有一些问题：
- [x] ~~mod大多停留在1.12.2，lang格式还是json？~~ 都可以使用。
- [x] ~~如果还有更高版本的，格式是什么？~~ 看mod。
- [x] ~~无法自主选择自己所需的mod内容。~~ 脚本已适配。
- [ ] mod内容不全。
- [ ] 可能无人维护。
下列问题解决请colla打勾。讨论在这里进行。

**Comment by lakejason0** [comment]
1. 目前的脚本不支持1.12.2的模组内容添加。
2. `.json`只是用于读取的。

**Comment by Dianliang233** [comment]
情况已有所改善。
