### ISSUE TITLE
日常更新如何操作

### ISSUE THREAD

**Issue by lakejason0** [Teahouse-Studios/mcwzh-meme-resourcepack#55]
1. 先按照[这里](https://github.com/dianliang233/minecraft-lzh/issues/16)的要求去更新文言文。
2. 根据英文文件的变化去更新。
其中，如果翻译关键字（键）被修改了的话，请不要改动键，而是复制一份键值对，值保留原来的值。
如果参数发生了变化，视情况在repo的`optional/`下新建增补文件。
所有的键值对按照翻译关键字的字母排列顺序排列。
3. 改动成梗体的样子。如果暂时没有想法，请选择Crowdin的正确（而不总是第一个）翻译。

感谢各位！

最新进度：
- [x] 1.16.2

**Comment by lakejason0** [comment]
最后一次更新到：1.16-pre4。

**Comment by AlPha5130** [comment]
近几个版本没有已知的更多更改了。

**Comment by AlPha5130** [comment]
此指导已不再符合当前情况，现予以关闭。
