### ISSUE TITLE
加载画面修改

### ISSUE THREAD

**Issue by CR-019** [Teahouse-Studios/mcwzh-meme-resourcepack#99]
bugjump了解一下
![bugjang](https://ftp.bmp.ovh/imgs/2020/07/bf45242c696c6845.jpg)
![bugjump](https://ftp.bmp.ovh/imgs/2020/07/5ff055659de77649.gif)

**Comment by lakejason0** [comment]
1.16的你要会做就做。

**Comment by lakejason0** [comment]
1.15以下的做过了。

**Comment by CR-019** [comment]
minecraft\textures\gui\title\mojangstudios



在 2020-07-18 17:55:02，"lakejason0" <notifications@github.com> 写道：

1.16的你要会做就做。

**Comment by lakejason0** [comment]
直接把这个图片提供过来啦——

**Comment by CR-019** [comment]
![mojangstudios](https://user-images.githubusercontent.com/56062674/87851516-0e119a00-c92c-11ea-925b-8df740972ab1.png)

**Comment by lakejason0** [comment]
这都糊了，你用firefox send发过来吧。

**Comment by lakejason0** [comment]
记得把图的出处表明一下。

**Comment by CR-019** [comment]
https://ftp.bmp.ovh/imgs/2020/07/fcd36a0f45c6b26e.png
没对齐，故意的。
游戏内使用效果：
https://ftp.bmp.ovh/imgs/2020/07/fcd36a0f45c6b26e.png

**Comment by lakejason0** [comment]
还是很糊，并且也没给出处。是你自己做的吗？

**Comment by CR-019** [comment]
这个是对齐了的，https://ftp.bmp.ovh/imgs/2020/07/7c117cf468fae752.png
我自己做的
部分修复了一下糊的问题

**Comment by lakejason0** [comment]
> 这个是对齐了的，https://ftp.bmp.ovh/imgs/2020/07/7c117cf468fae752.png
> 我自己做的
> 部分修复了一下糊的问题

把彩边用白色糊掉就没问题了吗（（
看上去观感不算好，不过会采纳的。

**Comment by lakejason0** [comment]
采纳后会在pack.mcmeta内写上你的名字。

**Comment by lakejason0** [comment]
经测试文件似乎并不生效。

**Comment by CR-019** [comment]
红的背景里面看不见彩边（（
我的ps技术太烂了（
做了一个歪歪扭扭的版本：https://ftp.bmp.ovh/imgs/2020/07/e608f0b3d6237d48.png (
去金蛋工作室那里下了字体包，重做了一个，应该不糊了：https://ftp.bmp.ovh/imgs/2020/07/307d5b9d0532e98f.png
经测试需要optifine

**Comment by lakejason0** [comment]
字体包的话……他们的协议可能不行。你知道他们所发布的字体是出自哪里吗？是Mojang自己的字体吗？还是他们自己做的？

**Comment by CR-019** [comment]
他们自己做的仿制

**Comment by lakejason0** [comment]
协议是个问题。他们有说自己作品的协议吗？或者把原帖链接给我一下。

**Comment by CR-019** [comment]
上面是他们在b站的发布帖

**Comment by lakejason0** [comment]
![image](https://user-images.githubusercontent.com/36039861/88008447-ddf01400-cb42-11ea-8d37-de0ce2e48ce1.png)
看到了，但是……

**Comment by lakejason0** [comment]
之后会在帖子里写上的。

**Comment by lakejason0** [comment]
已推送到`module-dev`分支。

**Comment by CR-019** [comment]
额，抱歉，请问需要回复什么？

**Comment by lakejason0** [comment]
直接知了就是了（
在`module-dev`合并到主分支后这个更改你们就能看到了。

**Comment by AlPha5130** [comment]
已合并
